import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';

import { tailwindClass } from '@/utils/tailwindcss';
import '@/styles/globals.css';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={tailwindClass(
          'flex min-h-dvh flex-col font-sans text-base leading-normal text-black antialiased',
          // inter.className,
        )}
      >
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
